
<h1 align="center" style="color: whitesmoke">Welcome to ZendyBlog</h1>

<div align="center" style="padding-left: 20%; padding-right: 20%; margin-top: 10%; color: white;">
    <h2>This is a blog where you can register and create your posts</h2>
    <h2>You can see each others posts and its Author</h2>
    <h2>You can isolate and see just your posts</h2>
    <h2>You can edit and delete your posts</h2>
    <h2>And many more interesting stuff</h2>
</div>