<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Zendy</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <?php echo $this->headLink()->appendStylesheet('/dist/css/bootstrap.css') ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
    <![endif]-->
</head>
<body background="/images/background.jpg">
<!--<body> background="/images/background.jpg"-->
<!--Navigation-->
<?php
$logedIn = Zend_Auth::getInstance()->hasIdentity();
$login = "block";
$logout = "hidden";
    if($logedIn)
    {
        $login = "none";
        $logout = "block";
    }else {
        $login = "block";
        $logout = "none";
    }
?>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index/index">Zendy</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="/index/index">Home</a></li> <!--class="active"-->
                <li><a href="/post/index">Posts</a></li>
                <li style="display: <?php echo $logout; ?> "><a href="/post/myposts">My Posts</a></li>
                <li style="display: <?php echo $logout; ?> "><a href="/post/create">Create post</a></li>
                <li><a href="/about/index">About</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li style="display: <?php echo $login; ?> "><a href="/authentication/register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li style="display: <?php echo $login; ?> "><a href="/Authentication/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                <li style="display: <?php echo $logout; ?> "><a href="/Authentication/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--EndNavigation-->
<?php  ?>
<?php echo $this->layout()->content; ?>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="/dist/js/myCustom.js" type="text/javascript"></script>
</body>
</html>