
<h1 align="center" style="color: whitesmoke">About ZendyBlog</h1>

<div align="center" style="padding-left: 20%; padding-right: 20%; margin-top: 3%; color: white;">
	<h2 style=" margin-bottom: 3%;">This is a first version, and until now we did:</h2>
	<h4 align="left">Login and Register with custom hashing using blowfish algorithm</h4>
	<h4 align="left">See Posts of other users</h4>
	<h4 align="left">See just your posts</h4>
	<h4 align="left">Create your posts using tinyMCE editor, which supports a lot of tools including inserting images & videos from url</h4>
	<h4 align="left">Edit your posts using tinyMCE editor</h4>
	<h4 align="left">Delete your post</h4>

	<h4 align="left">Set category of your post from dropDown</h4>


	<h2 style=" margin-bottom: 3%;">In Progress:</h2>
	<h4 align="left">Comment each others posts <span style="margin-left: 2%" class="glyphicon glyphicon-pencil" aria-hidden="true"></span></h4>
	<h4 align="left">Like each others posts <span style="margin-left: 2%" class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></h4>
</div>